# These settings are synced to GitHub by https://probot.github.io/apps/settings/

_extends: .github

repository:
  name: NucleosSitemapBundle
  description: ðŸ”— This bundle provides some classes for an automatic sitemap.xml generation.
  homepage: https://nucleos.rocks
  topics: hacktoberfest, symfony, symfony-bundle, bundle, php, sitemap, sitemal-xml

branches:
  - name: main
    protection:
      enforce_admins: false
      required_status_checks:
        contexts:
          - "Coding Standards (8)"
          - "Static Code Analysis (8.1)"
          - "Test (PHP 8, symfony 4.4, lowest)"
          - "Test (PHP 8, symfony 5.1, lowest)"
          - "Test (PHP 8, symfony 4.4, highest)"
          - "Test (PHP 8, symfony 5.1, highest)"
          - "Test (PHP 8.1, symfony 4.4, lowest)"
          - "Test (PHP 8.1, symfony 5.1, lowest)"
          - "Test (PHP 8.1, symfony 4.4, highest)"
          - "Test (PHP 8.1, symfony 5.1, highest)"
          - "Code Coverage (8.1)"
          - "Mutation Tests (8.1)"
        strict: true

      required_pull_request_reviews: null
      restrictions: null
